routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/home', function () {
//     return view('home');
// });


Route::resource('trips','TripController');
Route::resource('users','UserController');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('home/created', 'HomeController@myTrips')->name('home.created');
Route::get('home/reserved', 'HomeController@myReservedTrips')->name('home.reserved');

Route::get('users/{user}/trips', 'UserController@trips')->name('users.trips');

Route::patch('trips/{trip}/reserve', 'TripController@reserve')->name('trips.reserve');
Route::patch('trips/{trip}/unreserve', 'TripController@unreserve')->name('trips.unreserve');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Профиль</div>

                <div class="panel-body">
                    
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @elseif (session('danger'))
                        <div class="alert alert-danger">
                            {{ session('danger') }}
                        </div>
                    @endif

                        <p>Имя: {{ $user->name}}</p>
                        <p>E-mail: {{ $user->email}}</p>

                    <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}">
                        Редактировать профиль
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection