routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/home', function () {
//     return view('home');
// });


Route::resource('trips','TripController');
Route::resource('users','UserController');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('home/created', 'HomeController@myTrips')->name('home.created');
Route::get('home/reserved', 'HomeController@myReservedTrips')->name('home.reserved');

Route::get('users/{user}/trips', 'UserController@trips')->name('users.trips');

Route::patch('trips/{trip}/reserve', 'TripController@reserve')->name('trips.reserve');
Route::patch('trips/{trip}/unreserve', 'TripController@unreserve')->name('trips.unreserve');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function trips()
    {
        return $this->hasMany(\App\Models\Trip::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Models\User;
use App\Models\Trip;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
     {
         $this->middleware('auth');
     }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('id', Auth::id())->get();
        return view('users.index', ['users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        if (isset($user)) {
            return view('users.show', compact('user'));
        } else {
            return redirect()->route('home')
                ->with('danger', 'Ошибка доступа или нет такого пользователя');            
        }
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function trips($id)
     {
         $trips = Trip::where('id_user', $id)->paginate(5);
         $count = Trip::where('id_user', $id)->count();
         return view('trips.index', compact('trips', 'count'))
           ->with('i', (request()->input('page', 1) - 1) * 5);
     }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($id == Auth::id()) {
            $user = User::find($id);
            return view('users.edit', compact('user'));
        } else {
            return redirect()->route('home')
                ->with('danger', 'Ошибка доступа');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'name' => 'string|max:25',
            // 'email' => 'string|email|max:25|unique:users',
            // 'password' => 'string|min:6|confirmed',
        ]);

        $user = User::where('id', Auth::id())->find($id);        
        if (isset($user)) {
            $user->update($request->all());
            return redirect()->route('home')
                ->with('success', 'Успешное обновление профиля!');
        } else {
            return redirect()->route('home')
                ->with('danger', 'Ошибка доступа');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Trip::where('id', Auth::id())->find($id);
        if (isset($user)){
            $user->update(['id_role' => 5]);
            return redirect()->route('register')
                ->with('success', 'Пользователь успешно удален');
        } else {
            return redirect()->route('home')
                ->with('danger', 'Ошибка доступа');
        }
    }
}

resources/views/users/created.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Всего добавлено {{$count}}</div>

                <div class="panel-body">
                    
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @elseif (session('danger'))
                        <div class="alert alert-danger">
                            {{ session('danger') }}
                        </div>
                    @endif
                    
                    @foreach ($trips as $trip)
                    {!! Form::open(['method' => 'DELETE','route' => ['trips.destroy', $trip->id], 'class' => 'form-horizontal']) !!}                    
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="pointA" class="col-md-4 control-label">Откуда</label>
                            <div class="col-md-6">
                                <input id="pointA" type="text" name="pointA" value="{{$trip->pointA}}" disabled class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pointB" class="col-md-4 control-label">Куда</label>
                            <div class="col-md-6">
                                <input id="pointB" type="text" name="pointB" value="{{$trip->pointB}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="price" class="col-md-4 control-label">Цена</label>
                            <div class="col-md-6">
                                <input id="price" type="text" name="price" value="{{$trip->price}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="seat_quantity" class="col-md-4 control-label">Количество мест</label>
                            <div class="col-md-6">
                                <input id="seat_quantity" type="number" name="seat_quantity" value="{{$trip->seat_quantity}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="reserved" class="col-md-4 control-label">Уже забронировано</label>
                            <div class="col-md-6">
                                <input id="reserved" type="number" name="reserved" value="{{$trip->reserved}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="start_time" class="col-md-4 control-label">Начало поездки</label>
                            <div class="col-md-6">
                                <input id="start_time" type="datetime" name="start_time" value="{{$trip->start_time->format('d m Y H:s')}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="break" class="col-md-4 control-label">Остановка</label>
                            <div class="col-md-6 switch">
                                <input id="break" type="checkbox" name="break" class="form-control"
                                <?php if ($trip->break == 'on') { echo 'checked="checked"';}?> disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a class="btn btn-primary" href="{{ route('trips.edit',$trip->id) }}">Изменить</a>
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </div>
                        </div>
                        <hr>
                    </form>
                    @endforeach
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Изменение профиля</div>

                <div class="panel-body">
                      
                    {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id], 'class' => 'form-horizontal']) !!}
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Имя</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name"
                                    value="{{ $user->name }}">

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" 
                                    value="{{$user->email}}">
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Пароль</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password-confirm') ? ' has-error' : '' }}">
                            <label for="password-confirm" class="col-md-4 control-label">Подтверждение</label>

                            <div class="col-md-6 switch">
                                <input id="password-confirm" type="password" class="form-control" name="password-confirm">

                                @if ($errors->has('password-confirm'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password-confirm') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Сохранить
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Профиль</div>

                <div class="panel-body">
                   
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @elseif (session('danger'))
                        <div class="alert alert-danger">
                            {{ session('danger') }}
                        </div>
                    @endif

                    You are logged in!

                    @foreach ($users as $user)
                        <p>Имя: {{ $user->name}}</p>
                        <p>E-mail: {{ $user->email}}</p>
                    @endforeach

                    <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}">
                        Редактировать профиль
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/reserved.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Всего забрнировано {{$count}}</div>

                <div class="panel-body">
                    
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @elseif (session('danger'))
                        <div class="alert alert-danger">
                            {{ session('danger') }}
                        </div>
                    @endif
                    
                    @foreach ($trips as $trip)
                    {!! Form::open(['method' => 'PATCH','route' => ['trips.unreserve', $trip->id_trip], 'class' => 'form-horizontal']) !!}
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="pointA" class="col-md-4 control-label">Откуда</label>
                            <div class="col-md-6">
                                <input id="pointA" type="text" name="pointA" value="{{$trip->pointA}}" disabled class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pointB" class="col-md-4 control-label">Куда</label>
                            <div class="col-md-6">
                                <input id="pointB" type="text" name="pointB" value="{{$trip->pointB}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="price" class="col-md-4 control-label">Цена</label>
                            <div class="col-md-6">
                                <input id="price" type="text" name="price" value="{{$trip->price}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="seat_quantity" class="col-md-4 control-label">Количество мест</label>
                            <div class="col-md-6">
                                <input id="seat_quantity" type="number" name="seat_quantity" value="{{$trip->seat_quantity}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="reserved" class="col-md-4 control-label">Уже забронировано</label>
                            <div class="col-md-6">
                                <input id="reserved" type="number" name="reserved" value="{{$trip->reserved}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="start_time" class="col-md-4 control-label">Начало поездки</label>
                            <div class="col-md-6">
                                <input id="start_time" type="datetime" name="start_time" value="{{$trip->start_time->format('d m Y H:s')}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="break" class="col-md-4 control-label">Остановка</label>
                            <div class="col-md-6 switch">
                                <input id="break" type="checkbox" name="break" class="form-control"
                                <?php if ($trip->break == 'on') { echo 'checked="checked"';}?> disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="reserved_seat" class="col-md-4 control-label">Мною забронировано ({{$trip->reserved_seat}})</label>
                        
                            <div class="col-md-6">
                                <select name="reserved_seat" id="reserved_seat" class="form-control" required>
                                    @for ($i = 1; $i <= $trip->reserved_seat; $i++)
                                        <option value="{{$i}}">{{ $i }}</option>
                                    @endfor
                                </select>
                                @if ($errors->has('reserved_seat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('reserved_seat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a class="btn btn-info" href="{{ route('trips.show',$trip->id_trip) }}">Посмотреть</a>
                                <button type="submit" class="btn btn-danger">Отменить</button>

                            </div>
                        </div>
                        <hr>
                    </form>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Просмотр пользователя {{$user->name}}</div>

                <div class="panel-body">
                
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @elseif (session('danger'))
                        <div class="alert alert-danger">
                            {{ session('danger') }}
                        </div>
                    @endif

                    <form class="form-horizontal">
                        <div class="form-group{{ $errors->has('photo') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label"></label>

                            <div class="col-md-6">
                                <img src="{{ $user->photo }}" alt="{{ $user->name }}" name="photo">
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Имя</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name"
                                    value="{{ $user->name }}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" 
                                    value="{{$user->email}}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('birth') ? ' has-error' : '' }}">
                            <label for="birth" class="col-md-4 control-label">Дата рождения</label>

                            <div class="col-md-6">
                                <input id="birth" type="text" class="form-control" name="birth" 
                                    value="{{$user->birth}}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('birth_place') ? ' has-error' : '' }}">
                            <label for="birth_place" class="col-md-4 control-label">Город</label>

                            <div class="col-md-6">
                                <input id="birth_place" type="text" class="form-control" name="birth_place" 
                                    value="{{$user->birth_place}}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                            <label for="gender" class="col-md-4 control-label">Пол</label>

                            <div class="col-md-6">
                                <input id="gender" type="text" class="form-control" name="gender" 
                                    value="{{$user->gender}}" disabled>
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('experience') ? ' has-error' : '' }}">
                            <label for="experience" class="col-md-4 control-label">Опыт</label>

                            <div class="col-md-6">
                                <input id="experience" type="text" class="form-control" name="experience" 
                                    value="{{$user->experience}}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('trip_count') ? ' has-error' : '' }}">
                            <label for="trip_count" class="col-md-4 control-label">Поездки</label>

                            <div class="col-md-6">
                                <input id="trip_count" type="text" class="form-control" name="trip_count" 
                                    value="{{$user->trip_count}}" disabled>
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('about') ? ' has-error' : '' }}">
                            <label for="about" class="col-md-4 control-label">О себе</label>

                            <div class="col-md-1">
                                <input id="like" type="text" class="form-control" name="like" 
                                    value="{{$user->like}}" disabled>
                            </div>

                            <div class="col-md-1">
                                <input id="music" type="text" class="form-control" name="music" 
                                    value="{{$user->music}}" disabled>
                            </div>

                            <div class="col-md-1">
                                <input id="smoke" type="text" class="form-control" name="smoke" 
                                    value="{{$user->smoke}}" disabled>
                            </div>
                            
                            <div class="col-md-1">
                                <input id="talk" type="text" class="form-control" name="talk" 
                                    value="{{$user->talk}}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('id_model') ? ' has-error' : '' }}">
                            <label for="id_model" class="col-md-4 control-label">Авто</label>

                            <div class="col-md-6">
                                <input id="id_model" type="text" class="form-control" name="id_model" 
                                    value="{{$user->id_model}}" disabled>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('rating') ? ' has-error' : '' }}">
                            <label for="rating" class="col-md-4 control-label">Рейтинг</label>

                            <div class="col-md-6">
                                <input id="rating" type="text" class="form-control" name="rating" 
                                    value="{{$user->rating}}" disabled>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">Написать</button>
                                <a class="btn btn-primary" href="{{route('trips.index')}}">Назад</a>
                            </div>
                        </div>                            
                        <hr>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection