routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/home', function () {
//     return view('home');
// });


Route::resource('trips','TripController');
Route::resource('users','UserController');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('home/created', 'HomeController@myTrips')->name('home.created');
Route::get('home/reserved', 'HomeController@myReservedTrips')->name('home.reserved');

Route::get('users/{user}/trips', 'UserController@trips')->name('users.trips');

Route::patch('trips/{trip}/reserve', 'TripController@reserve')->name('trips.reserve');
Route::patch('trips/{trip}/unreserve', 'TripController@unreserve')->name('trips.unreserve');

app/Models/Trip.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Trip extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
     protected $fillable = [
        'pointA', 'pointB', 'price', 'seat_quantity', 'start_time', 'break', 'id_user', 'reserved'
    ];

    protected $dates = ['start_time'];

    public function users()
    {
        return $this->belongsTo(\App\Models\User::class,'id_user','id');
    }

    public function scopeSearchByKeyword($query, $from, $to, $date)
    {
        if ($from!='' and $to!='' and $date!='') {
            $query->where(function ($query) use ($from, $to, $date) {
                $query->where("pointA", "LIKE","%$from%");                
                $query->where("pointB", "LIKE","%$to%");
                $query->where("start_time", "LIKE","%$date%");            
            });
        } elseif ($from!='' and $to!='') {
            $query->where(function ($query) use ($from, $to) {
                $query->where("pointA", "LIKE","%$from%");
                $query->where("pointB", "LIKE","%$to%");
            });
        } elseif ($from!='' and $date!='') {
            $query->where(function ($query) use ($from, $date) {
                $query->where("pointA", "LIKE","%$from%");
                $query->where("start_time", "LIKE","%$date%");            
            });  
        } elseif ($from!='') {
            $query->where(function ($query) use ($from) {
                $query->where("pointA", "LIKE","%$from%");
            });
        } elseif ($to!='' and $date!='') {
            $query->where(function ($query) use ($to, $date) {
                $query->where("pointB", "LIKE","%$to%");
                $query->where("start_time", "LIKE","%$date%");            
            });
        } elseif ($to!='') {
            $query->where(function ($query) use ($to) {
                $query->where("pointB", "LIKE","%$to%");
            });
        } elseif ($date!='') {
            $query->where(function ($query) use ($date) {
                $query->where("start_time", "LIKE","%$date%");            
            });
        }
        return $query;
    }
}

app/Http/Controllers/TripController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use App\Models\Trip;
use App\Models\User;
use App\Models\ReservedTrip;
use DB;

class TripController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
     
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = DB::table('cities')->pluck('city');        
        $pointA = \Request::get('pointA');
        $pointB = \Request::get('pointB');
        $start_time = \Request::get('start_time');
        if (isset($pointA) or isset($pointB) or isset($start_time)) {
            $trips = Trip::SearchByKeyword(
                $pointA,
                $pointB,
                $start_time
                )->paginate(5);
            $count = $trips->count();
        } else {
            $trips = Trip::latest()->paginate(5);
            $count = $trips->count();
        }
        return view('trips.index', compact('trips', 'count', 'cities'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = DB::table('cities')->pluck('city');
        return view('trips.create', compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            request()->validate([
            'pointA' => 'required',
            'pointB' => 'required',
            'price' => 'required',
            'seat_quantity' => 'required',
            'start_time' => 'required',
            // 'start_time' => 'required|date_format:d/m/Y|after:tomorrow',
            ]);
        $trip = new Trip;
        $trip->fill($request->all());
        $trip->id_user = Auth::id();
        $trip->save();
        return redirect()->route('home.created')
            ->with('success', 'Поездка успешно добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $trip = Trip::find($id);
        if (isset($trip)) {
            $trip->increment('view');
            return view('trips.show', compact('trip'));
        } else {
            return redirect()->route('trips.index')
                ->with('danger', 'Ошибка доступа или нет такой поездки');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cities = DB::table('cities')->pluck('city');
        $trip = Trip::where('id_user', Auth::id())->find($id);
        if (isset($trip)) {
            return view('trips.edit', compact('trip', 'cities'));
        } else {
            return redirect()->route('trips.index')
                ->with('danger', 'Ошибка доступа');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'pointA' => 'required',
            'pointB' => 'required',
            'price' => 'required',
            'seat_quantity' => 'required',
            'start_time' => 'required',
            'break' => 'required',
        ]);
        $trip = Trip::where('id_user', Auth::id())->find($id);
        if (isset($trip)) {
            $trip->update($request->all());
            return redirect()->route('home.created')
                ->with('success', 'Успешное обновление поездки');
        } else {
            return redirect()->route('home.created')
                ->with('danger', 'Ошибка при обновлении');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $trip = Trip::where('id_user', Auth::id())->find($id);
        if (isset($trip)) {
            $trip->delete();
            return redirect()->route('home.created')
                ->with('success', 'Поездка успешно удалена');
        } else {
            return redirect()->route('home.created')
                ->with('danger', 'Ошибка доступа');
        }
    }

    /**
     * Update the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function reserve(Request $request, $id)
    {
        $trip = Trip::where([
            ['id', $id],
            ['seat_quantity', '>', 0],
            ['id_user', '<>', Auth::id()]
        ])->find($id);
        
        if (isset($trip)) {
            $reserved = Reservedtrip::where([
                ['id', Auth::id()],
                ['id_trip', $id]
            ])->find(Auth::id());

            request()->validate([
                'reserved_seat' => 'required|integer',
            ]);

            if (isset($reserved)) {
                $reserved->increment('reserved_seat', $request->reserved_seat);
            } else {
                $reserved = new Reservedtrip;
                $reserved->id = Auth::id();
                $reserved->id_trip = $id;
                $reserved->reserved_seat = $request->reserved_seat;
                $reserved->save();
            }

            $trip->increment('reserved', $request->reserved_seat);
            $trip->decrement('seat_quantity', $request->reserved_seat);
             
            return redirect()->route('home.reserved')
                ->with('success', 'Поездка успешно забронирован');
        } else {
            return redirect()->route('trips.index')
                ->with('danger', 'Ошибка при бронировании');
        }
    }

    /**
     * Update the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function unreserve(Request $request, $id)
    {
        $trip = Trip::where([
            ['id', $id],
            ['reserved', '>', 0],
            ['id_user', '<>', Auth::id()]
            ])->find($id);
        if (isset($trip)) {
            $reserved = Reservedtrip::where([
                ['id', Auth::id()],
                ['id_trip', $id],
                ['reserved_seat', '>=', 1]
            ])->find(Auth::id());
            
            request()->validate([
                'reserved_seat' => 'required|integer',
            ]);

            $reserved_seat = $request->reserved_seat;
            
            if (isset($reserved)) {
                if ($reserved->reserved_seat == $reserved_seat or
                $reserved->reserved_seat <= 1) {
                    $reserved->delete(Auth::id());
                } else {
                    $reserved->decrement('reserved_seat', $reserved_seat);
                }
            } else {
                return redirect()->route('home.reserved')
                    ->with('danger', 'Ошибка при отмене бронировании111');
            }

            $trip->decrement('reserved', $reserved_seat);
            $trip->increment('seat_quantity', $reserved_seat);

            return redirect()->route('home.reserved')
                ->with('success', 'Бронирование успешно отменено');
        } else {
            return redirect()->route('home.reserved')
                ->with('danger', 'Ошибка при отмене бронировании');
        }
    }
}

resources/views/trips/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Добавление поездки</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('trips.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('pointA') ? ' has-error' : '' }}">
                            <label for="pointA" class="col-md-4 control-label">Откуда</label>

                            <div class="col-md-6">
                                <select name="pointA" id="pointA" class="form-control" required autofocus>
                                    @foreach ($cities as $city)
                                    <option value="{{$city}}">{{$city}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('pointA'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('pointA') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('pointB') ? ' has-error' : '' }}">
                            <label for="pointB" class="col-md-4 control-label">Куда</label>

                            <div class="col-md-6">
                                <select name="pointB" id="pointB" class="form-control" required autofocus>
                                    @foreach ($cities as $city)
                                    <option value="{{$city}}">{{$city}}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('pointB'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('pointB') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                            <label for="price" class="col-md-4 control-label">Цена</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control" name="price"
                                    value="{{ old('price') }}" required>

                                @if ($errors->has('price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('seat_quantity') ? ' has-error' : '' }}">
                            <label for="seat_quantity" class="col-md-4 control-label">Количество мест</label>

                            <div class="col-md-6">
                                <input id="seat_quantity" type="number" class="form-control" name="seat_quantity" 
                                    value="{{ old('seat_quantity') }}" min="1" max="20" required>
                                
                                @if ($errors->has('seat_quantity'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('seat_quantity') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('start_time') ? ' has-error' : '' }}">
                            <label for="start_time" class="col-md-4 control-label">Начало поездки</label>

                            <div class="col-md-6">
                            <input id="start_time" type="date" class="form-control" name="start_time"
                                value="{{ old('start_time') }}" required>
                            
                                @if ($errors->has('start_time'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_time') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('break') ? ' has-error' : '' }}">
                            <label for="break" class="col-md-4 control-label">Остановка</label>

                            <div class="col-md-6 switch">
                                <input id="break" type="checkbox" class="form-control" name="break">

                                @if ($errors->has('break'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('break') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Добавить
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/trips/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Изменение поездки</div>

                <div class="panel-body">

                    {!! Form::model($trip, ['method' => 'PATCH','route' => ['trips.update', $trip->id], 'class' => 'form-horizontal']) !!}
                        {{ csrf_field() }}
                        
                        <div class="form-group{{ $errors->has('pointA') ? ' has-error' : '' }}">
                            <label for="pointA" class="col-md-4 control-label">Откуда</label>

                            <div class="col-md-6">
                                <select name="pointA" id="pointA" class="form-control" required autofocus>
                                    <option value="{{$trip->pointA}}">{{$trip->pointA}}</option>                                    
                                    @foreach ($cities as $city)
                                    <option value="{{$city}}">{{$city}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('pointA'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('pointA') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('pointB') ? ' has-error' : '' }}">
                            <label for="pointB" class="col-md-4 control-label">Куда</label>

                            <div class="col-md-6">
                                <select name="pointB" id="pointB" class="form-control" required autofocus>
                                    <option value="{{$trip->pointB}}">{{$trip->pointB}}</option>
                                    @foreach ($cities as $city)
                                    <option value="{{$city}}">{{$city}}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('pointB'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('pointB') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                            <label for="price" class="col-md-4 control-label">Цена</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control" name="price"
                                    value="{{ $trip->price }}" required>

                                @if ($errors->has('price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('seat_quantity') ? ' has-error' : '' }}">
                            <label for="seat_quantity" class="col-md-4 control-label">Количество мест</label>

                            <div class="col-md-6">
                                <input id="seat_quantity" type="number" class="form-control" name="seat_quantity" 
                                    value="{{ $trip->seat_quantity }}" min="1" max="20" required>
                                @if ($errors->has('seat_quantity'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('seat_quantity') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('start_time') ? ' has-error' : '' }}">
                            <label for="start_time" class="col-md-4 control-label">Начало поездки</label>

                            <div class="col-md-6">
                                <input id="start_time" type="date" class="form-control" name="start_time"
                                    value="{{ $trip->start_time }}" required>

                                @if ($errors->has('start_time'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_time') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('break') ? ' has-error' : '' }}">
                            <label for="break" class="col-md-4 control-label">Остановка</label>

                            <div class="col-md-6 switch">
                                <input id="break" type="checkbox" class="form-control" name="break"
                                    <?php if ($trip->break == 'on') echo 'checked="checked"';?>
                                >

                                @if ($errors->has('break'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('break') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Сохранить
                                </button>
                                <a class="btn btn-primary" href="{{url('home/created')}}">Назад</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/trips/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Всего {{$count}}</div>

                <div class="panel-body">
                    
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @elseif (session('danger'))
                        <div class="alert alert-danger">
                            {{ session('danger') }}
                        </div>
                    @endif
                    
                    {!! Form::open(['method'=>'GET','route'=>'trips.index','class'=>'form-horizontal'])  !!}
                        <div class="input-group custom-search-form">
                            <span class="input-group-btn">
                                <div class="col-md-3">
                                    <select name="pointA" id="pointA" class="form-control">
                                        <option value="">Откуда</option>
                                        @foreach ($cities as $city)
                                            <option value="{{$city}}">{{$city}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select name="pointB" id="pointB" class="form-control">
                                        <option value="">Куда</option>
                                        @foreach ($cities as $city)
                                            <option value="{{$city}}">{{$city}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <input type="date" class="form-control" name="start_time" placeholder="Дата" value="">
                                </div>
                                <div class="col-md-3">
                                    <button class="btn btn-primary" type="submit" autofocus>
                                        Найти поездку
                                    </button>
                                </div>
                            </span>
                        </div>
                    {!! Form::close() !!}
                    <hr>
                    @foreach ($trips as $trip)
                    <form class="form-horizontal">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="pointA" class="col-md-4 control-label">Откуда</label>
                            <div class="col-md-6">
                                <input id="pointA" type="text" name="pointA" value="{{$trip->pointA}}" disabled class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pointB" class="col-md-4 control-label">Куда</label>
                            <div class="col-md-6">
                                <input id="pointB" type="text" name="pointB" value="{{$trip->pointB}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="price" class="col-md-4 control-label">Цена</label>
                            <div class="col-md-6">
                                <input id="price" type="text" name="price" value="{{$trip->price}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="seat_quantity" class="col-md-4 control-label">Количество мест</label>
                            <div class="col-md-6">
                                <input id="seat_quantity" type="number" name="seat_quantity" value="{{$trip->seat_quantity}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="reserved" class="col-md-4 control-label">Уже забронировано</label>
                            <div class="col-md-6">
                                <input id="reserved" type="number" name="reserved" value="{{$trip->reserved}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="start_time" class="col-md-4 control-label">Начало поездки</label>
                            <div class="col-md-6">
                                <input id="start_time" type="datetime" name="start_time" value="{{$trip->start_time->format('d m Y H:s')}}" disabled class="form-control">
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="break" class="col-md-4 control-label">Остановка</label>
                            <div class="col-md-6 switch">
                                <input id="break" type="checkbox" name="break" class="form-control"
                                <?php if ($trip->break == 'on') echo 'checked="checked"';?> disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a class="btn btn-info" href="{{ route('trips.show',$trip->id) }}">Перейти к бронированию</a>
                            </div>
                        </div>                            
                        <hr>
                    </form>
                    @endforeach
                    {{$trips->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection